name: Publish and Release

on:
  push:
    branches:
      - main

env:
  NODE_VERSION: 18

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    name: Publish and Release
    steps:
      - name: Checkout code
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          persist-credentials: false
      - name: Setup Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      - name: Prepare
        run: |
          npm ci
          npm run build
          npm test
      - name: Publish and Release
        uses: akashic-games/action-release@e4e3c8901b8ed92356c5eb9cf6cfc573a9c4ce9b # v2.1.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          npm_token: ${{ secrets.NPM_TOKEN }}
